server:
  port: 8081
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/spring_social
        username: root
        password: 123456789

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
    security:
      oauth2:
        client:
          registration:
            google:
              clientId: 796266675783-f3kb476envpa6hpuiecc502dh6f6e7bk.apps.googleusercontent.com
              clientSecret: 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
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - profile
            facebook:
              clientId: 316433600303321
              clientSecret: dffd3837b5e06dd16af2ab531a888c02
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - public_profile
            github:
              clientId: 081ae4ad372f0e7da86b
              clientSecret: e57f095ae0dc1b24ded2f78309bdb470cb0d8b10
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - user:email
                - read:user
          provider:
            facebook:
              authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
              tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
              userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect